services:
  - type: web
    name: emotion-detector
    env: python
    region: oregon
    plan: free
    buildCommand: python3.11 -m pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --preload --timeout 300
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9