services:
  - type: web
    name: emotion-detector
    env: docker
    region: oregon
    plan: free
    dockerCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --preload --timeout 300
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9